### ISSUE TITLE
Console errors..

### ISSUE THREAD

**Issue by floq-design** [ahmedam55/sassSolution#9]
Hi
Getting the following errors in console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "main in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SassSolution.sublime-package", line 12, in on_activated
  File "main in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SassSolution.sublime-package", line 191, in runEngine
  File "main in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/SassSolution.sublime-package", line 66, in isSass
AttributeError: 'NoneType' object has no attribute 'endswith'
no such prop row_padding
```
Not sure if the last line `no such prop row_padding` is relevant but included it in case it is.
Cheers
James

**Comment by ahmedam55** [comment]
Hey James,
Thanks for that, I couldn't have noticed it without you. It's now fixed.
Thanks.
